"""Public API for Multi-Agent Governor."""

__version__ = "0.2.1"

from .adaptive_evaluation import (
    AdaptiveTrialOutcome,
    AdaptiveTrialSpec,
    adaptive_outcome_from_report,
    build_adaptive_run_payload,
    build_adaptive_trial_matrix,
    build_fixed_run_payload,
    compare_adaptive_to_fixed,
    derive_pilot_review_signals,
    fixed_outcome_from_report,
    render_review_prompt,
    summarize_adaptive_outcomes,
)
from .adapters import CodexCliRuntime, CodexCliRuntimeConfig, ScriptedRuntime
from .evidence import (
    DecisionAction,
    DecisionReceipt,
    EvidenceFact,
    EvidenceSource,
)
from .events import JsonlEventSink, MemoryEventSink, RunEvent, load_events
from .fixed_execution import FixedCountController, FixedExecutionReport
from .execution import (
    AdaptiveController,
    AgentRequest,
    AgentResult,
    AggregatedResult,
    ConcatenatingAggregator,
    ExecutionCheckpoint,
    ExecutionReport,
    ExecutionTask,
    JsonFindingsAggregator,
    ReviewEvidenceVerifier,
    VerificationResult,
    WorkUnit,
)
from .evaluation import (
    AdjudicationVerdict,
    BlindAdjudication,
    CheckpointObservation,
    CoverageObservation,
    DatasetSplit,
    DefectSeverity,
    GoldDefect,
    ReviewFinding,
    ReviewTask,
    ScoreReport,
    TaskSource,
    TaskStatus,
    TrialOutcome,
    TrialSpec,
    UsageObservation,
    build_trial_matrix,
    materialize_task,
    parse_codex_exec_jsonl,
    scan_materialized_task,
    score_findings,
    summarize_outcomes,
    validate_task_assets,
)
from .models import (
    BaselineObservation,
    Budget,
    Decision,
    Mode,
    RoundObservation,
    ScalingReview,
    StopReason,
    TaskSignals,
)
from .policy import Governor
from .runtime import GovernorSession
from .telemetry import add_usage, with_governance_tokens

__all__ = [
    "__version__",
    "AdaptiveTrialOutcome",
    "AdaptiveTrialSpec",
    "AdjudicationVerdict",
    "AdaptiveController",
    "AgentRequest",
    "AgentResult",
    "AggregatedResult",
    "BaselineObservation",
    "BlindAdjudication",
    "Budget",
    "CheckpointObservation",
    "CodexCliRuntime",
    "CodexCliRuntimeConfig",
    "ConcatenatingAggregator",
    "CoverageObservation",
    "DatasetSplit",
    "DecisionAction",
    "DecisionReceipt",
    "DefectSeverity",
    "Decision",
    "EvidenceFact",
    "EvidenceSource",
    "ExecutionCheckpoint",
    "ExecutionReport",
    "ExecutionTask",
    "FixedCountController",
    "FixedExecutionReport",
    "GoldDefect",
    "Governor",
    "GovernorSession",
    "JsonFindingsAggregator",
    "JsonlEventSink",
    "MemoryEventSink",
    "Mode",
    "ReviewFinding",
    "ReviewEvidenceVerifier",
    "ReviewTask",
    "RoundObservation",
    "ScoreReport",
    "ScriptedRuntime",
    "ScalingReview",
    "StopReason",
    "TaskSource",
    "TaskStatus",
    "TaskSignals",
    "TrialOutcome",
    "TrialSpec",
    "UsageObservation",
    "VerificationResult",
    "WorkUnit",
    "RunEvent",
    "add_usage",
    "adaptive_outcome_from_report",
    "build_adaptive_run_payload",
    "build_adaptive_trial_matrix",
    "build_fixed_run_payload",
    "build_trial_matrix",
    "compare_adaptive_to_fixed",
    "derive_pilot_review_signals",
    "fixed_outcome_from_report",
    "materialize_task",
    "load_events",
    "parse_codex_exec_jsonl",
    "render_review_prompt",
    "scan_materialized_task",
    "score_findings",
    "summarize_outcomes",
    "summarize_adaptive_outcomes",
    "validate_task_assets",
    "with_governance_tokens",
]
